# Generated by Django 6.0.4 on 2026-07-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities_name', models.CharField(blank=True, max_length=130, null=True)),
                ('facilities_name_gu', models.CharField(blank=True, max_length=130, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPreferred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=130, null=True)),
                ('preferred_name_gu', models.CharField(blank=True, max_length=130, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=130, null=True)),
                ('type_name_gu', models.CharField(blank=True, max_length=130, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=500, null=True)),
                ('property_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('property_price_period', models.CharField(choices=[('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('year', 'Per Year')], default='month', max_length=10)),
                ('property_bhk_type', models.CharField(blank=True, choices=[('1_rk', '1 RK/Room'), ('1_bhk', '1 BHK'), ('2_bhk', '2 BHK'), ('3_bhk', '3 BHK'), ('4_bhk', '4 BHK'), ('5_bhk', '5 BHK'), ('5_plus_bhk', '5+ BHK')], max_length=10, null=True)),
                ('property_purpose', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale'), ('pg/hostel', 'PG/Hostel')], default='rent', max_length=10)),
                ('property_contact', models.JSONField(blank=True, default=list, null=True)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('property_facilities', models.ManyToManyField(blank=True, to='propertys.propertyfacility')),
                ('property_preferred', models.ManyToManyField(blank=True, to='propertys.propertypreferred')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='propertys.propertytype')),
            ],
        ),
    ]
