# Generated by Django 6.0.4 on 2026-07-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytypes',
            name='type_name_gu',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
