# Generated by Django 6.0.4 on 2026-07-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_contact",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
