# Generated by Django 6.0.4 on 2026-07-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertys", "0002_alter_property_property_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
