# Generated by Django 6.0.4 on 2026-07-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertys', '0003_propertyperferred'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities_name', models.CharField(blank=True, max_length=130, null=True)),
                ('facilities_name_gu', models.CharField(blank=True, max_length=130, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
