# Generated by Django 6.0.4 on 2026-07-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_is_superuser"),
        ("propertys", "0004_propertyaddress_propertyphoto"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PropertyAddress",
            new_name="PropertyLocation",
        ),
    ]
