# Generated by Django 6.0.4 on 2026-08-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertys", "0005_rename_propertyaddress_propertylocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyphoto",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property/%Y/%m/%d/"
            ),
        ),
    ]
