# Generated by Django 6.0.4 on 2026-08-13 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertys", "0006_alter_propertyphoto_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="propertys.propertytype",
            ),
        ),
    ]
