# Generated by Django 6.0.4 on 2026-08-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertys", "0007_alter_property_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_bhk_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1rk", "1 RK/Room"),
                    ("1bhk", "1 BHK"),
                    ("2bhk", "2 BHK"),
                    ("3bhk", "3 BHK"),
                    ("4bhk", "4 BHK"),
                    ("5bhk", "5 BHK"),
                    ("5plusbhk", "5+ BHK"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
