# Generated by Django 6.0.4 on 2026-08-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertys", "0008_alter_property_property_bhk_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyphoto",
            name="display_order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
