# Generated by Django 6.0.4 on 2026-08-23 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_city_latitude_city_longitude_countrycode_latitude_and_more"),
        ("propertys", "0009_alter_propertyphoto_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="propertylocation",
            name="address_line",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="propertylocation",
            name="area",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="propertylocation",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.city",
            ),
        ),
        migrations.AlterField(
            model_name="propertylocation",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.countrycode",
            ),
        ),
        migrations.AlterField(
            model_name="propertylocation",
            name="landmark",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="propertylocation",
            name="pincode",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="propertylocation",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="propertys.property",
            ),
        ),
        migrations.AlterField(
            model_name="propertylocation",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.state",
            ),
        ),
        migrations.AlterField(
            model_name="propertyphoto",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property/photos/"
            ),
        ),
        migrations.AlterField(
            model_name="propertyphoto",
            name="image_title",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="propertyphoto",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="propertys.property",
            ),
        ),
    ]
