# Generated by Django 6.0.4 on 2026-08-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertys", "0010_property_slug_alter_property_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertylocation",
            name="property",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="propertys.property",
            ),
        ),
    ]
