# Generated by Django 6.0.4 on 2026-07-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileaddresses",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profileaddresses",
            name="longitued",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
    ]
