# Generated by Django 6.0.4 on 2026-06-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_portalprofile_city_and_more"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresses",
            name="profile_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="accounts.userprofile",
            ),
        ),
    ]
