# Generated by Django 6.0.4 on 2026-07-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_profileaddresses_delete_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileaddresses',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
