# Generated by Django 6.0.4 on 2026-07-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_profileaddresses_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileaddresses',
            old_name='is_defualt',
            new_name='is_default',
        ),
    ]
