# Generated by Django 6.0.4 on 2026-07-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
