# Generated by Django 6.0.4 on 2026-06-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_phone",
            field=models.CharField(
                blank=True, db_index=True, max_length=30, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                fields=("country_code", "phone"), name="unique_country_phone"
            ),
        ),
    ]
