# Generated by Django 6.0.4 on 2026-04-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
    ]
