# Generated by Django 6.0.4 on 2026-06-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_portalprofile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalprofile",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.language",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.language",
            ),
        ),
    ]
