# Generated by Django 6.0.4 on 2026-08-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="city_name_gu",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="state_name_gu",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
