# Generated by Django 6.0.4 on 2026-08-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_city_city_name_gu_state_state_name_gu"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="countrycode",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="countrycode",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=12, null=True
            ),
        ),
    ]
