# Generated by Django 6.0.4 on 2026-07-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_portalprofile_language_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycode',
            name='country_name_gu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
