# Generated by Django 6.0.4 on 2026-09-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_city_latitude_city_longitude_countrycode_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cities",
                to="accounts.state",
            ),
        ),
    ]
